blank_issues_enabled: true
contact_links:
  - name: Report a security vulnerability (Refer to Security policy)
    url: https://github.com/KarolinHem/TESTING/security/policy
    about: Please review our security policy for more details
  - name: GitHub Discussions
    url: https://github.com/KarolinHem/TESTING/discussions
    about: Join in-depth discussions or ask questions
    
